nelmio_api_doc:
    documentation:
        info:
            title: Test Ubitransport
            description: This is a ubitransport test api
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
